### ISSUE TITLE
[BUG] Back button in GUI not working

### ISSUE THREAD

**Issue by GallowsDove** [Slimefun-Addon-Community/LiteXpansion#18]
## Description (REQUIRED)

The "back" book in slimefun GUI on the UU-Matter Recipes page is possible to be grabbed and thrown out, doesn't go back to previous page, making the player stuck on the page.

## Steps to reproduce the Issue (REQUIRED)

1. Open guide
2. Open the UU-Matter Recipes page
3. Attempt to go back

## Expected behavior (REQUIRED)

It should bring you back to the previous page.

## Server Log

![image](https://user-images.githubusercontent.com/71831019/104766525-090e9580-576b-11eb-8b7b-91c0bc168100.png)

## Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/71831019/104766380-bd5bec00-576a-11eb-9399-dfdbcac15451.png)

**Comment by Seggan** [comment]
LX needs to update dependencies

**Comment by oahawhool** [comment]
Couple things. the 'book' button can be put into a grindstone and converted into a regular book.
Also, it is possible to get out of that page by crouching while hitting the back button.

**Comment by J3fftw1** [comment]
Try to use the latest version and report it agian

**Comment by GallowsDove** [comment]
Appears to be fixed in the latest version
