### ISSUE TITLE
Metal Forge not respecting amounts

### ISSUE THREAD

**Issue by ReformedHooper** [Slimefun-Addon-Community/LiteXpansion#19]
## Description (REQUIRED)
if you would craft an iridium plate you would need 4 iridium and 4 advanced alloy and 1 diamond. but i found an bug if you put in there 1 diamond and 1 iridium and 1 advanced alloy it basicly do the same

![bug](https://user-images.githubusercontent.com/62069758/104837797-2b152e80-58b7-11eb-8f08-a9fa3d45ea9a.png)

 - Server Software (Spigot/Paper): YATOPIA 1.16.5
 - Minecraft version: 1.16.5
 - CS-CoreLib version: DEV - 92
 - Slimefun version: DEV - 780
 - LiteXpansion version: DEV - 120

**Comment by J3fftw1** [comment]
Might be related to #13
