### ISSUE TITLE
[BUG] Back button dont work in UU matter section inside guide.

### ISSUE THREAD

**Issue by j19mes** [Slimefun-Addon-Community/LiteXpansion#20]
## Description (REQUIRED)
In the slimefun guide when you click the UU matter section it breaks & the back button wont let you go back to the main men.

## Steps to reproduce the Issue (REQUIRED)
1) Open slimefun guide
2) Click UU matter
3) Try to press the back button in the left.

## Expected behavior (REQUIRED)
The back button will not work & you will be unable to return to the main guide without a server restart.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft version:  1.16.4
 - CS-CoreLib version: DEV 91
 - Slimefun version: RC 18
 - LiteXpansion version: DEV 123

**Comment by J3fftw1** [comment]
:notlikethis:
update slimefun
