### ISSUE TITLE
[BUG] Illegal Stack Size (3)

### ISSUE THREAD

**Issue by MrLarkyy** [Slimefun-Addon-Community/LiteXpansion#24]
![image](https://user-images.githubusercontent.com/48769171/106658166-3a75c680-659d-11eb-864d-6b3087df42d1.png)

I just updated SF and all addons to latest stable versions and when I just took a look into our console, there was this warning.

 - Server Software (Spigot/Paper):
 - Minecraft version: 1.16.5
 - CS-CoreLib version:
 - Slimefun version:
 - LiteXpansion version:

**Comment by J3fftw1** [comment]
duplicate also you didnt fill in the bug report
