### ISSUE TITLE
[BUG] Mining and Diamond drill break RestrictedCreative plugin creative protected blocks

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#26]
## Description (REQUIRED)

The RestrictedCreative disable the block items dropped when break if placed out in the creative mode.

## Steps to reproduce the Issue (REQUIRED)

1. Use the Diamond or Mining drill on the creative placed blocks.
2. The Diamond or Mining drill breaks the RestrictedCreative block protection and blocks dropped to floor.

## Expected behavior (REQUIRED)

The Diamond or Mining drill no breaks the RestrictedCreative block protection.

## Environment (REQUIRED)

[21:15:30 INFO]: This Server uses the following setup of Slimefun:
Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Installed Addons: (4)
  RestrictedCreative v2.4.6
  SlimefunFix v2.0
  LiteXpansion vDEV - 125 (git 96d1cf20)
  FluffyMachines vDEV - 64 (git 582f5de7)

**Comment by J3fftw1** [comment]
wrong close but this is an issue on dough / protection plugin not litexpansion
