### ISSUE TITLE
[BUG] Console spammed with errors

### ISSUE THREAD

**Issue by TheDevTec** [Slimefun-Addon-Community/LiteXpansion#28]
## Description (REQUIRED)
No such field error - Console errors

## Steps to reproduce the Issue (REQUIRED)
https://pastebin.com/U4ex7ULg

## Expected behavior (REQUIRED)
Console is spammed with errors

## Environment (REQUIRED)
 - Server Software (Spigot/Paper): Paper - Yatopia
 - Minecraft version: git-Yatopia-ver/1.16.5-26 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
 - CS-CoreLib version: none
 - Slimefun version: vDEV - 819 (git 854c3335
 - LiteXpansion version: vDEV - 124 (git 0e449831)

**Comment by J3fftw1** [comment]
Update to the latest version
