### ISSUE TITLE
Nerf some addon items

### ISSUE THREAD

**Issue by WalshyDev** [Slimefun-Addon-Community/LiteXpansion#29]
Nerf the following items:
* DyntaTech generators
* Infinity generators
* Chicken addon stuff

**Comment by TheBusyBiscuit** [comment]
:monkaS: wut

**Comment by WalshyDev** [comment]
They generate too much power. We don't like that

**Comment by TheBusyBiscuit** [comment]
:LUL:

**Comment by WalshyDev** [comment]
We already nerf energised. It only does 64/32 now

**Comment by TheBusyBiscuit** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/PluginManager.html#disablePlugin(org.bukkit.plugin.Plugin)

:eyes:

**Comment by ProfElements** [comment]
👀 Really coming for my addon 😢

**Comment by WalshyDev** [comment]
To be fair, i had a look and didn't see anything OP. Not exactly sure what should be nerfed /shrug

**Comment by ProfElements** [comment]
I think the only think that would be any concern to yall would probably be the durability generator
