### ISSUE TITLE
[BUG] Power Unit Color miss

### ISSUE THREAD

**Issue by xMikux** [Slimefun-Addon-Community/LiteXpansion#3]
## Description (REQUIRED)
Power Unit item color name miss

## Steps to reproduce the Issue (REQUIRED)
Open Guide and go to LiteXpansion category.
Find Power Unit and look the item name.
![2020-12-21_19 45 45](https://user-images.githubusercontent.com/26039249/102774070-3b73df80-43c5-11eb-8800-3da0254b3ba5.png)

## Expected behavior (REQUIRED)
Item have correct color, and don't have &.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper v1_16_R3
 - Minecraft version: 1.16.4
 - CS-CoreLib version: CS-CoreLib vDEV - 92 (git e9150d72)
 - Slimefun version: vDEV - 768 (git 2c4c7579)
 - LiteXpansion version: vDEV - 103 (git 77b7d391)

**Comment by J3fftw1** [comment]
yea you are using a modified LiteXpansion version

**Comment by J3fftw1** [comment]
Thanks for reporting.
Also, i have been working on translating LiteXpansion. if this is up you dont have to run your own fork any longer.

**Comment by xMikux** [comment]
Okay!
