### ISSUE TITLE
[BUG] Electric Chestplate errors when shoot player with some projectiles

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#30]
## Description (REQUIRED)

Electric Chestplate errors when shoot player with some projectiles.

## Steps to reproduce the Issue (REQUIRED)

If a player throws a player wearing an electric chestplate with an egg or snowball or enderpearl the plugin writes this errors.

## Expected behavior (REQUIRED)

Electric Chestplate no writes errors when shoot player with some projectiles

## Server Log

https://pastebin.com/DjMDbPTG

## Environment (REQUIRED)

[13:37:56 INFO]: This Server uses the following setup of Slimefun:
Tuinity git-Tuinity-"a539774" (MC: 1.16.5)
Slimefun DEV - 819 (git 854c3335)
Metrics-Module #21
Java 11

Installed Addons: (11)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  RestrictedCreative v2.4.6
  ExtraTools vDEV - 24 (git 791c7468)
  PomaExpansion vDEV - 15 (git f4bb6859)
  SlimefunFix v2.0
  SFCalc vDEV - 15 (git 6586cb3f)
  LiteXpansion vDEV - 128 (git 3d1408a5)
  EcoPower vDEV - 3 (git 18ba903d)
  ExtraGear vDEV - 12 (git 4570ea2c)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)
  FluffyMachines vDEV - 65 (git a7af4837)

**Comment by WalshyDev** [comment]
Fixed in 051a79635de1b79a70dfc0030577bda543171d5c

**Comment by andris155** [comment]
Thanks!
