### ISSUE TITLE
[BUG] UU-Matter recipes not work in Slimefun Auto-Crafter

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#35]
## Description (REQUIRED)

UU-Matter recipes not work in Slimefun Auto-Crafter.

## Steps to reproduce the Issue (REQUIRED)

1. Give and build Slimefun Auto-Crafters system.
2. Right click with item that can be made of UU-Matter.
3. UU-Matter recipe not selectable.

## Expected behavior (REQUIRED)

UU-Matter recipes works in Slimefun Auto-Crafter.

## Server Log

none

## Environment (REQUIRED)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 864 (git 82366191)
Metrics-Module #21
Java 11

Installed Addons: (5)
  InfinityExpansion vDEV - 100 (git 65892de0)
  LiteXpansion vDEV - 138 (git 004e3c61)
  SlimefunFix v3.0
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 90 (git 9f27da61)

**Comment by J3fftw1** [comment]
fixed in f4bbceafc76dbf28ae18860ef358839cd80adf95
