### ISSUE TITLE
[BUG] Plugin does not load

### ISSUE THREAD

**Issue by andris155** [Slimefun-Addon-Community/LiteXpansion#36]
## Description (REQUIRED)

The plugin does not load.

## Steps to reproduce the Issue (REQUIRED)

1. Update to the latest version (DEV 143 (git 01658))
2. Start server

## Expected behavior (REQUIRED)

The plugin will load.

## Server Log

https://pastebin.com/yD11uvah

## Environment (REQUIRED)

Tuinity git-Tuinity-"94f025a" (MC: 1.16.5)
Slimefun DEV - 869 (git 18139bb5)
Metrics-Module #21
Java 11
LiteXpansion - DEV 143 (git 01658)

**Comment by WalshyDev** [comment]
That is not build 143, that's build 142. 143 fixes this bug and was released shortly after 142. Update.

**Comment by TheBusyBiscuit** [comment]
@WalshyDev You Ci skipped, there was no new build :P

**Comment by WalshyDev** [comment]
Incorrect, I CI Skipped the LICENSE revert. The actual fix was not skipped. You can also see he is using 142 (with the bug) with the hash.

**Comment by TheBusyBiscuit** [comment]
ehm no....
The log says 143 too. And you can look up the hash, it points to the bug.
And the actual fix **was** skipped... You ci skipped... so there was no build.

**Comment by WalshyDev** [comment]
Wait, the builds repo skipped it because of last thing yeah. REEE waiting for a build and then pushing revert was needed. Stupid build repo

**Comment by TheBusyBiscuit** [comment]
You wrote that code...

**Comment by WalshyDev** [comment]
Exactly :p
