### ISSUE TITLE
[BUG] LiteXpansion would not load upon server start

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/LiteXpansion#40]
## Description (REQUIRED)

The plugin didn't load upon server start. There's an error in the log. See below

## Steps to reproduce the Issue (REQUIRED)

See log

## Expected behavior (REQUIRED)

The plugin to load

## Server Log

https://pastebin.com/SQWgQ3Xc

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): paper 552
 - Minecraft version: 1.16.5
 - CS-CoreLib version: removed
 - Slimefun version: Dev 881
 - LiteXpansion version: Dev 145

**Comment by WalshyDev** [comment]
Fixed in next build, ty
