### ISSUE TITLE
Can't craft any metal forge recipe

### ISSUE THREAD

**Issue by Overseer9** [Slimefun-Addon-Community/LiteXpansion#42]
## Description (REQUIRED)
I tried to make gold plate in metal forge multi block, and it didn't make anything

## Steps to reproduce the Issue (REQUIRED)
- build metal forge
- put gold ingot inside the dispenser
- right click the wall
video
https://youtu.be/0_CVt2Z7Fs0

## Expected behavior (REQUIRED)
- the metal forge crafts gold plate

## Server Log
https://pastebin.com/Jma89MER

## Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/81430883/116643906-a7cea300-a9a4-11eb-87bd-3cf28ade20fe.png)

**Comment by Boomer-1** [comment]
I was able to confirm this bug on Dev 146.
