### ISSUE TITLE
[BUG] Error clicking on electric machine

### ISSUE THREAD

**Issue by paulobiazao** [Slimefun-Addon-Community/LiteXpansion#44]
## Description (REQUIRED)

I cannot open any electrical machine, and an error appears on the console when I try.

## Steps to reproduce the Issue (REQUIRED)

1 - Place an electric machine on the floor;
2 - Click on it to open.

## Expected behavior (REQUIRED)

The expected behavior is for the electrical machine to open and without any error on the console.

## Server Log

https://pastebin.com/DcBtiGx8

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): 1.16.5
 - Minecraft version: 1.16.5
 - CS-CoreLib version:
 - Slimefun version: 896
 - LiteXpansion version: 147

**Comment by J3fftw1** [comment]
You are using an outdated version

**Comment by paulobiazao** [comment]
Yes, I am aware, but the situation in the latest version is worse, as the machines have become blocks of Vanilla.

**Comment by J3fftw1** [comment]
Can you send the error log of that

**Comment by Boomer-1** [comment]
I'm in dev 148 and can open all blocks and nothing has turned into vanilla blocks yet. can you provide details so others can evaluate paulobiazao?

**Comment by paulobiazao** [comment]
https://pastebin.com/PQjtqp05

**Comment by paulobiazao** [comment]
The same error came back, not being able to open an interface of the machines

**Comment by paulobiazao** [comment]
![print](https://user-images.githubusercontent.com/49761518/116833498-d2308400-ab8f-11eb-976f-1e1d8128b0ea.PNG)
