### ISSUE TITLE
[BUG] Startup errors

### ISSUE THREAD

**Issue by mrcoffee1026** [Slimefun-Addon-Community/LiteXpansion#46]
## Description (REQUIRED)
Errors on every startup.

## Steps to reproduce the Issue (REQUIRED)
Start server with litexpansion included, note the logs.

## Expected behavior (REQUIRED)
No errors on startup.

## Server Log
latest.log: https://pastebin.com/5WrkQUCg

## Environment (REQUIRED)
Paper git-Paper-683 (MC: 1.16.5)
Slimefun DEV - 912 (git f4b47331)
Metrics-Module #22
Java 11

Installed Addons: (34)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  FoxyMachines vDEV - 45 (git ce4f8193)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 40 (git f3e782d3)
  SimpleMaterialGenerators vDEV - 6 (git 2083e132)
  DynaTech vDEV - 116 (git dfb785ea)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 10 (git 660e2ce6)
  InfinityExpansion vDEV - 111 (git 461a3fd6)
  SFCalc vDEV - 22 (git 4e764de8)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  PrivateStorage vDEV - 17 (git 43d35d74)
  TranscEndence vDEV - 33 (git e9b4de1a)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)
  FluffyMachines vDEV - 81 (git 67fa6406)
  CMI v8.8.4.1
  ChestTerminal vDEV - 43 (git 3096bab5)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  SoundMuffler vDEV - 20 (git cde78980)
  SlimefunWarfare vDEV - 33 (git d0fa13c2)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  ExoticGarden vDEV - 76 (git d148a362)
  Liquid vDEV - 11 (git bea52454)
  SlimeCustomizer vDEV - 6 (git 6c348829)
  LiteXpansion vDEV - 125 (git 96d1cf20)
  SimpleUtils vDEV - 8 (git 1505dfa3)
  SoulJars vDEV - 22 (git aded79dd)
  SlimyRepair vDEV - 3 (git c56293bb)
>

**Comment by J3fftw1** [comment]
Update to latest
