### ISSUE TITLE
LiteXpansion it does not work in new versions of the paper.

### ISSUE THREAD

**Issue by MizukageMaTes** [Slimefun-Addon-Community/LiteXpansion#47]
## Description (REQUIRED)

In the new versions of the paper the LiteXpansion plugin are not working...
In my case I use tuinity, which is a paper fork... but the error comes from the paper according to the tests I performed.

## Steps to reproduce the Issue (REQUIRED)

Place LiteXpansion.jar in the server's plugins folder in the current versions of the paper and load the server.

## Expected behavior (REQUIRED)

That the plugin loads normally...

## Server Log

![ErrorLiteXpansion](https://user-images.githubusercontent.com/42588556/120372745-f0ec7c80-c2ed-11eb-8bb9-0efa55a4d14e.png)

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft version:
 - CS-CoreLib version:
 - Slimefun version:
 - LiteXpansion version:
![image](https://user-images.githubusercontent.com/42588556/120372771-fe096b80-c2ed-11eb-83ac-2ccd0e9c298e.png)

**Comment by J3fftw1** [comment]
it loads successfully for me with the latest paper #756 to be exactly.

**Comment by MizukageMaTes** [comment]
Ah, right the problem was the presence of CSCore-Lib! Thanks and sorry for the unnecessary topic!

**Comment by J3fftw1** [comment]
Its fine dont worry. Bugs can happen so it could have been a real issue
