### ISSUE TITLE
Change energy produced by Advanced Solar Panel

### ISSUE THREAD

**Issue by GalaxyKat11** [Slimefun-Addon-Community/LiteXpansion#48]
I believe the energy produced by an Advanced Solar Panel should be increased for both day and night. It currently only yields 80 j/t during the day and 10 j/t at night. These figures may have been appropriate when the previous recipe to craft an advanced Solar Panel only required a solar panel in the center of the recipe. The current recipe requires the center spot of the recipe to be an Energized Solar Panel. Since the Energized Solalr Panel itself generates 256 j/t during the day and 128 j/t at night, it seems only right that using one to craft an upgraded Panel should yield higher numbers. Suggesting 400 j/t during day and 200 j/t at night.

**Comment by J3fftw1** [comment]
The energized solar panel generates 2 timee less when LiteXpansion is installed also, the advanced solar panel its internal buffer is way.bigger then the buffer from the energized.

**Comment by GalaxyKat11** [comment]
So with LiteXpansion installed the energized only actually generates 128 during day and 64 at night. This is still more than what you get if you use it to craft an advanced. Although the buffer will be a benefit, I think most people are looking at energy produced when making any solar panels

**Comment by WalshyDev** [comment]
It doesn't need to generate the same or even more, it's a stepping stone into much higher energy generators.

**Comment by J3fftw1** [comment]
You need to craft it to make better panels aswell soo it can be seen as a recipe item

**Comment by GalaxyKat11** [comment]
Ok, I guess you saw this and intended these results. I thought it was an oversight when recipe was changed.

**Comment by shui-suan** [comment]
In the latest LiteXpansion, the formulation of advanced solar panels can no longer synthesize more advanced solar generators, so should the formula be modified???

**Comment by J3fftw1** [comment]
What are you talking about?
Also this is a really old issue 
So either open a new one and describe the bug
or join the discord and discuss it there
