### ISSUE TITLE
Ancient Pedestal is changing renamed items from an anvil making some of the items usable in Slimefun. 

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun-Addon-Community/LiteXpansion#49]
## Description (REQUIRED)
Ancient Pedestal is clearing the 'italic' of renamed items on an anvil and making it usable on Slimefun recipe system. Items that works are that has no color on it.
Iridium

## Steps to reproduce the Issue (REQUIRED)

    Obtain a vanilla version of the item which is sugar, in this steps I'll be using salt as an example.
    Obtain an anvil and the exp.
    Rename your items to 'Salt' (Case sensitive!).
    Put it on Ancient Pedestal and take it back.
    Try to use it on the crafting system.

https://youtu.be/EZZ_Zc8G9xA

## Expected behavior (REQUIRED)
Ancient Pedestal should not reset the name.

## Server Log
n/a

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
https://user-images.githubusercontent.com/34732414/125150328-27c57600-e169-11eb-86ae-f5a82a0278fb.png
Latest LX version

This issue is linked to https://github.com/Slimefun/Slimefun4/issues/3164. When this issue is fixed this will be fixed aswell!

**Comment by WalshyDev** [comment]
Fixed in Slimefun DEV - 951
