### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eghbalTG** [Slimefun-Addon-Community/LiteXpansion#50]
![image](https://user-images.githubusercontent.com/22130034/131260979-8aa8965f-5e8f-4a75-be6a-a3840cdab32c.png)

 - Server Software (Spigot/Paper): Paper
 - Minecraft version: 1.16.5
 - CS-CoreLib version: no have
 - Slimefun version: 962
 - LiteXpansion version: 154

**Comment by J3fftw1** [comment]
not an issue since its on startup
