### ISSUE TITLE
[BUG] UU Crafter disappeared after crafting a few items.

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/LiteXpansion#55]
## Description (REQUIRED)

I started by crafting the diamond recipe. I added 40 UU matter, and it proceeded to craft 4 diamonds. as soon as i closed the gui, the machine disappeared. 

## Steps to reproduce the Issue (REQUIRED)

so far I cannot reproduce it. I'm going to update paper and try the recipes for a while to see if it happens again

## Expected behavior (REQUIRED)

machine to not disappear

## Server Log

https://pastebin.com/qap6u5Dk
https://pastebin.com/kfeNgS6E

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): 209 Paper
 - Minecraft version: 1.17.1
 - CS-CoreLib version: n/a
 - Slimefun version: dev 984
 - LiteXpansion version: dev 157

**Comment by J3fftw1** [comment]
Wait you cant reproduce it even though you gave reproducing steps in the description??

**Comment by Boomer-1** [comment]
just happened again

i updated paper and while i was in the crafter it disappeared with another error log.

https://pastebin.com/1fmd3rcz
