### ISSUE TITLE
uu crafter does not work with cargo input nodes

### ISSUE THREAD

**Issue by NewToThis3402** [Slimefun-Addon-Community/LiteXpansion#60]
## Description (REQUIRED)

The uu crafter does not work with cargo input nodes. but works fine with output.

## Steps to reproduce the Issue (REQUIRED)

place down a uu crafter and a cargo manager
place down a cargo input node besides the uu crafter and make sure tha its connected with the cargo network
input node does not work. items do not go into the uu crafter as they should.

## Expected behavior (REQUIRED)

The items should go to the input slot of the uu crafter

## Server Log

there was no unexpected behavior in the console

## Environment (REQUIRED)
 

 - Server Software (Spigot/Paper):Paper
 - Minecraft version: 1.18
 - CS-CoreLib version: not installed
 - Slimefun version: dev 999
 - LiteXpansion version: dev 160

**Comment by J3fftw1** [comment]
tested it does work
feel free to record it if it doesnt
