### ISSUE TITLE
[BUG] Drill doesn't mine Deepslate and Ancient Debris

### ISSUE THREAD

**Issue by Edo2048** [Slimefun-Addon-Community/LiteXpansion#62]
## Description (REQUIRED)
Drill doesn't mine Deepslate and Ancient Debris

## Steps to reproduce the Issue (REQUIRED)
1. place Deepslate or Ancient Debris
2. try mine with Drill
3. doesn't work

## Expected behavior (REQUIRED)
Drill should mine Deepslate and Ancient Debris

## Environment (REQUIRED)
[17:54:28 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-152 (MC: 1.18.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #28
Java 17
Installed Addons: (2)
  LiteXpansion vDEV - 162 (git 30e9b239)
  SoulJars vDEV - 23 (git b8358a1f)

 - Server Software (Spigot/Paper): Paper
 - Minecraft version: 1.18.1
 - CS-CoreLib version:
 - Slimefun version: DEV - 999 (git e02eedd9)
 - LiteXpansion version: vDEV - 162 (git 30e9b239)

**Comment by J3fftw1** [comment]
fixed
