### ISSUE TITLE
[BUG] Refined Smeltery removes the block below the fire

### ISSUE THREAD

**Issue by marvjosh1** [Slimefun-Addon-Community/LiteXpansion#63]
## Description (REQUIRED)
When using the refined smeltery, it will remove the block below the fire too, and not just the fire.
This can break bedrock too.

## Steps to reproduce the Issue (REQUIRED)
Place down a refined smeltery.
Use it, watch the block below the fire be removed.
https://youtu.be/U1FLDQ-LoxA

## Expected behavior (REQUIRED)
Only the fire to be extiguished, not the block to be removed

## Server Log
n/a

## Environment (REQUIRED)
https://i.imgur.com/bxrqMDA.png
https://i.imgur.com/4uz8kiN.png

**Comment by WalshyDev** [comment]
Should be fixed in new build
