### ISSUE TITLE
[BUG] Multiblock Machines not working at all

### ISSUE THREAD

**Issue by marvjosh1** [Slimefun-Addon-Community/LiteXpansion#64]
## Description (REQUIRED)
Both the Refined Smeltery, and the Metal Forge do not process any recipes.

## Steps to reproduce the Issue (REQUIRED)
1. Install the newest LiteXpansion build
2. Try out using those machines
https://youtu.be/i2XRAcYWCI0

## Expected behavior (REQUIRED)
For the machines to work as intended

## Server Log
n/a

## Environment (REQUIRED)
https://i.imgur.com/h2JXiTc.png

**Comment by J3fftw1** [comment]
Update Litexpansion and report back if it doesnt work
