### ISSUE TITLE
Cargo Configurator does not clear node configuration when shift right click

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun-Addon-Community/LiteXpansion#65]
## Description (REQUIRED)

As stated, the cargo configurator does not clear the cargo node configuration when shift right clicking the node.

## Steps to reproduce the Issue (REQUIRED)

Configure a node on any channel other than 1, whitelist or blacklist, items in the node or not, round robin on or off, doesn't matter.
Shift right click the node and while in chat it will say the configuration has been cleared, nothing happens. When you shift right click in mid air the chat gets a message that the node configuration has been cleared.

## Expected behavior (REQUIRED)

for the configurator to clear the node back to it's default setup, and to not provide the chat message that the node has had its configuration cleared when shift right clicking in the air.

## Server Log

no errors in console or log

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper 175
 - Minecraft version: 1.18.1
 - CS-CoreLib version: n/a
 - Slimefun version: Dev 999
 - LiteXpansion version: 168

**Comment by J3fftw1** [comment]
talked on discord 
Fixed up the lore of the configurator had a typo in it to my understanding
