### ISSUE TITLE
[BUG] LiteXpansion yellow console warning: failed to change field generation with nerf-other-addons set to true

### ISSUE THREAD

**Issue by Blueray51** [Slimefun-Addon-Community/LiteXpansion#67]
## Description (REQUIRED)
When nerf-other-addons is set to true in config.yml, 3 yellow warnings are printed in the server console as shown below.

## Steps to reproduce the Issue (REQUIRED)
With nerf-other-addons: true in config.yml, the warning appears in the server console on every boot.

## Expected behavior (REQUIRED)
These warnings should not appear and field generation for these 3 items should change successfully.

## Server Log

![LiteXpansion warning](https://user-images.githubusercontent.com/46680428/156165753-6bfc2fff-caf2-4b80-9cb0-4ca8f3af6124.PNG)

## Environment (REQUIRED)
![SF Versions 1](https://user-images.githubusercontent.com/46680428/156166742-aac4db96-1182-4cfd-9162-964a2bc163f4.PNG)
![SF Versions 2](https://user-images.githubusercontent.com/46680428/156166760-73645974-9008-4f46-9b2b-0822aa342dd9.PNG)
![SF Versions 3](https://user-images.githubusercontent.com/46680428/156166782-38ea4285-e637-4f72-911d-7c3cf844ef46.PNG)
![SF Versions 4](https://user-images.githubusercontent.com/46680428/156166803-7a1864a9-2f5e-4f26-8eb9-61e3dfb442d1.PNG)

**Comment by J3fftw1** [comment]
fixed in latest :D
