### ISSUE TITLE
Charging 3 glass cutters at the same time

### ISSUE THREAD

**Issue by Fracticus** [Slimefun-Addon-Community/LiteXpansion#71]
## Description (REQUIRED)

I put 3 glass cutters in a charging bench, and it charged all 3 at the same time. The duration of charging didn't feel any longer than charging just 1. Then I've all 3 items in one slot an use that slot, it takes off energy from all 3 equally. 

## Steps to reproduce the Issue (REQUIRED)

Have 3 glass cutters in 1 slot, and cut glass. Put those glass cutters in a charging bench and wait.

![afbeelding](https://user-images.githubusercontent.com/102395700/163731108-4f3d108f-620c-4f6f-9265-3b909d552968.png)

## Expected behavior (REQUIRED)

I expected the charging bench to charge 1 glass cutter at a time, or take 3 times as long, or take 3 times as much power. When I cut with 3 items in a slot, I expect 1 to stay in that slot and the other 2 to go to a new one, so I end up using 1. The ghast tears look rly nice for this application, but unf they stack.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper 216
 - Minecraft version: 1.18.2
 - CS-CoreLib version:
 - Slimefun version: 999
 - LiteXpansion version: 160

**Comment by J3fftw1** [comment]
fixed in 0073b33
