### ISSUE TITLE
[BUG] Missing proper descriptions

### ISSUE THREAD

**Issue by RenanMsV** [Slimefun-Addon-Community/LiteXpansion#79]
## Description (REQUIRED)

MFE and MFSU do not have any descriptions, nor they show how much energy they store as they are capacitors.
A few other blocks from this addon also lack a description.

https://github.com/Slimefun-Addon-Community/LiteXpansion/blob/79885526e9c54b54807743f8f38aab815c0867b7/src/main/java/dev/j3fftw/litexpansion/Items.java#L364-L373

## Steps to reproduce the Issue (REQUIRED)

Just open the book and check LiteXpansion category.

## Expected behavior (REQUIRED)

I think it should have their descriptions on what they do like:
- MFE : Capacitor and charger with 4.000.000 J capacity that charges items at 12 J/t
- MFSU: Capacitor and charger with 40.000.000 J capacity that charges items at 52 J/t

## Server Log

Not required

## Environment (REQUIRED)

32

**Comment by Boomer-1** [comment]
that is intentionally designed that way for players to discover.

**Comment by RenanMsV** [comment]
I discovered by watching your video. If it was by making the item I dont think I would ever try making it.
But thats my suggestion, if another dev can confirm this is by design just close this issue.

**Comment by Boomer-1** [comment]
that's how panda and walshy made it. it's up to them if they want to close it or accept it

**Comment by J3fftw1** [comment]
All lore should be removed imo
