### ISSUE TITLE
[BUG]electric chestplate not negating damage even when charged, instead players are taking damage and dying

### ISSUE THREAD

**Issue by Ritwik-main** [Slimefun-Addon-Community/LiteXpansion#82]
## Description (REQUIRED)

electric chestplates are supposed to negate damage, but recently theyve been faulty and not stopping damage and letting it pass through to damage the player

## Steps to reproduce the Issue (REQUIRED)

charge a electric chestplate and wear it, then attempt to take damage, most of the times the electric chestplate wont work, i had made sure the electric chestplate was charged at all times 

## Expected behavior (REQUIRED)

electric chestplates should negate damage in the cost of charge lost

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft version:
 - CS-CoreLib version:
 - Slimefun version:
 - LiteXpansion version:
This Server uses the following setup of Slimefun:
Paper git-Paper-388 (MC: 1.19.3)
Slimefun 4.9-UNOFFICIAL
Metrics-Module #28
Java 17
Installed Addons: (25)
  Networks vDEV - 45 (git ade6fbd0)
  CrystamaeHistoria vDEV - 78 (git 340f1a94)
  AureliumSkills vBeta 1.3.13
  FoxyMachines vDEV - 61 (git 265728f9)
  RelicsOfCthonia vDEV - 8 (git a7ef6cb6)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  FNAmplifications vDEV - 84 (git dbbefc59)
  SFMG vSlimeCraftSMP
  DynaTech vSlimeCraft
  SFAdvancements vDEV - 23 (git 854eed14)
  SlimeHUD vDEV - 9 (git f831cd76)
  CMILib v1.2.4.5
  InfinityExpansion vSlimeCraft
  MobCapturer vDEV - 26 (git e0f006c2)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  SpiritsUnchained vDEV - 20 (git 5d5815a4)
  SlimeTinker vDEV - 77 (git 99a520b9)
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vSlimeCraft
  AlchimiaVitae vDEV - 24 (git 6950e5d2)
  HeadLimiter vDEV - 14 (git 0a02e2fd)
  ExoticGarden vSlimeCraft
  DankTech2 vDEV - 8 (git f2a8ab1f)
  LiteXpansion vDEV - 188 (git c0cb079e)

**Comment by Ritwik-main** [comment]
the cause might be aurelium skills, or some other non vanilla damage source that the electric chestplate doesnt recognise.

**Comment by Ritwik-main** [comment]
damages like tinker traits, aurelium skills

**Comment by Boomer-1** [comment]
its working perfect for me with mobs and lava until the charge is gone. you're also on an unofficial version of sf
